# Generated by Django 4.1 on 2023-05-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_strip_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='strip_id',
            new_name='stripe_id',
        ),
    ]
